services:
  database:
    container_name: glowbyte-pg
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: glow
      POSTGRES_USER: glow
      POSTGRES_DB: glow-db
    ports:
      - 5432:5432
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    command: >
      -c work_mem=256MB -c maintenance_work_mem=256MB -c max_wal_size=10GB -c max_connections=500
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
  pgadmin:
    container_name: glowbyte-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: glow@localhost.ru
      PGADMIN_DEFAULT_PASSWORD: glow
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      GUNICORN_ACCESS_LOGFILE: /dev/null
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
