services:
  app:
    container_name: glowbyte-seeder
    restart: no
    profiles: [ seed ]
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DSN: "host=glowbyte-pg user=postgres password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable TimeZone=Europe/Moscow"
  postgres:
    container_name: glowbyte-pg
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    command: >
      -c work_mem=256MB -c maintenance_work_mem=256MB -c max_wal_size=10GB -c max_connections=500
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10
  pgadmin:
    container_name: glowbyte-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      GUNICORN_ACCESS_LOGFILE: /dev/null
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
